version: "3.8"
services:
  worker:
    build: .
    environment:
      - API_HASH=${API_HASH}
      - API_ID=${API_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNELS=${CHANNELS}
      - DATABASE_URI=${DATABASE_URI}
      - ADMINS=${ADMINS}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOG_CHANNEL=${LOG_CHANNEL}
